name = "mistllc-backend-worker"
main = "dist/index.js"
compatibility_date = "2025-08-18"
worker_dev = "true"

[build]
command = "npm run build"

[vars]
VITE_API_BASE = "https://mistllc-backend-worker.jacobnixon59.workers.dev"

# Force ES Module format
compatibility_flags = ["nodejs_compat"]

[kv namespace]
binding = "mistllc"
id = "2d250836cc7d4adebb9d6a5968671077"

[placement]
mode = "smart"


