name = "mistllc-backend"
main = "src/index.ts"
compatibility_date = "2025-08-24"

[env.production]
name = "mistllc-backend"
route = "https://jacobnixon59.workers.dev/*"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "mistllc-db"

