name = "mistllc-backend"
main = "dist/index.ts"
compatibility_date = "2025-08-24"
preview_urls = "true"

[env.production]
name = "mistllc-backend"
route = "https://jacobnixon59.workers.dev/*"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "mistllc-db"
database_id = "8a00ac76-0737-4110-86e1-1c89e06f2421"

[assets]
directory = "./dist/index.ts"