name = "mistllc-backend"
main = "dist/index.js"
compatibility_date = "2025-08-23"
type = "javascript"

[build]
command = "npm run build"
[build.upload]
format = "service-worker"

[[d1_databases]]
binding = "DB"
database_name = "mistllc_db"

