version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: sh -c "cd frontend && npm run dev -- --host 0.0.0.0 --port 5173"
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "5173:5173"
    env_file:
      - .env

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: sh -c "cd backend && npx ts-node-dev --respawn src/index.ts"
    volumes:
      - ./backend:/app/backend
    ports:
      - "3000:3000"
    env_file:
      - .env

# Use this for prod deployment
# docker compose -f docker-compose.yml -f docker-compose.prod.yml up --build -d
