name: "Deploy MISTLLC"

on:
  push:
    branches: [ main ]
permissions:
    contents: read
    pull-requests: write
    deployments: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # FRONTEND -------------------
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: frontend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/frontend:latest
          build-args: |
            VITE_API_URL=${{ secrets.PROD_API_URL }}

      # BACKEND (image, optional) ---
      - name: Build backend image (dev/CI only)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: backend/Dockerfile
          push: false   # don’t push, local use only

      # BACKEND Deploy --------------
      - name: Publish backend Worker
        run: npx wrangler deploy
        working-directory: backend
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
